CREATE DATABASE IF NOT EXISTS sifm_lobar CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sifm_lobar;
CREATE TABLE IF NOT EXISTS users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS anggota(
 id INT AUTO_INCREMENT PRIMARY KEY,
 no_kta VARCHAR(40) NOT NULL UNIQUE,
 nama VARCHAR(120) NOT NULL,
 kategori ENUM('pengurus','kader','alumni') NOT NULL,
 jabatan VARCHAR(100),
 asal VARCHAR(100),
 tahun VARCHAR(4),
 foto VARCHAR(100),
 dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(kategori), INDEX(tahun)
);
CREATE TABLE IF NOT EXISTS admin(
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pengurus(
 id INT AUTO_INCREMENT PRIMARY KEY,
 no_kta VARCHAR(40) NOT NULL UNIQUE,
 nama VARCHAR(120) NOT NULL,
 jabatan VARCHAR(100),
 asal VARCHAR(100),
 tahun VARCHAR(4),
 foto VARCHAR(100),
 dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(tahun)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS kader(
 id INT AUTO_INCREMENT PRIMARY KEY,
 no_kta VARCHAR(40) NOT NULL UNIQUE,
 nama VARCHAR(120) NOT NULL,
 jabatan VARCHAR(100),
 asal VARCHAR(100),
 tahun VARCHAR(4),
 foto VARCHAR(100),
 dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(tahun)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS alumni(
 id INT AUTO_INCREMENT PRIMARY KEY,
 no_kta VARCHAR(40) NOT NULL UNIQUE,
 nama VARCHAR(120) NOT NULL,
 jabatan VARCHAR(100),
 asal VARCHAR(100),
 tahun VARCHAR(4),
 foto VARCHAR(100),
 dibuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(tahun)
) ENGINE=InnoDB;
